env:
  global:
  - REGISTRY_USERNAME=catac
  # GITHUB_TOKEN
  - secure: BYHR93T+t00xp5aXiKNd6NVReiGbIq01Llwt0Hiu8b0lByVSdvWZLMTZJpypwATHTK8C/Mvvlug9w6EHieopdDnd58d5buEsyuMtv79EgERm8DK2U2+VWceDTrHPnKbV6njTgcHQ18km3AU3EfbotCh7hQftJSCFjxHUtBMF24VymP5EQecJyh42iIwitnZiGp6q7sQUUZz/9lr7SS+WLywtQ4xrG2BkjzJIhJ+KavFtlQW4NhLmyJkfbdPkBagER16+gXD+LaOc3QrrhRkSIGn1ojqVqi+O8NZlGoK2s9AdVK7cXlawQ3in5irug2eHnDN9Yh0xfj+nsSTy3bedPYV6ESjlZTQ2+JCMCbxEIYCfsOonNSkacLW0/Asq8p4048uhVumUpoDcu8DCmvAG4YRn9JS4cwZXmfDCzWPwzRAlAvzVO9s+k5+yuC2vXwjlkoBynW0O0x5TeiuTYIAM4ZgQbh1LtQa/h1FEGm7+yoCNbTqLB8QtuOAecInyFqu2+M2iMsIDvKh8ZIt9bhwt9YEh0Ge8tED0SruNkdsypMz08SoQ/chTTpyeozgIFqA5rH47nMWzak98mmh87AHImGM/WoNiB93jie8OfQy71Y7pE1uvn8gguRxowAAUQ8c9RbWVWigq2i68cbaKaXBinzb5LLTdIB3kOI15OX5t++E=
  # REGISTRY_PASSWORD
  - secure: 0dZ2k0tAujm9R6EVtc02UXsByTU71GzlTrYI4XkM9nOZwBWjoM9j2d/bpCo9Xe/W5K4n+XDzBj+q/BymvbsaqRuxOxIT/tJJkS8hpOeEnfn4hLLJeelHF1YWbvDFLsfE/hu4EQnSGDwNXaWTKmqh2A1jGQyNNhNIYRKhTzPIvyzKU2X99/JPUtk0ZsB9AprVoHOVh2+7S0m/UQ2ro4LNQV7goIdVSxI92yPkqVWUIOhC5qoC8kgWrEcVjJW9dfnYxRNJrlXPpknyrU4Up2CqeapDbhbQlDL+B5aPRMMkGCtWtA4dSv8TVF8dP5hU29+yzLpY7CQ9017spVTUN81EW8fj8Vu5geWDP7CHPgMCtVaDUpiW2DZoeSX88YbpFy/H+iRueHLED51xyncDjSgeYd+pOD+sjetYunnLKEgUuvtBQ1mlqSPS32uydfZ/MuhLsC3O6AP/oGaIcVIOfCzTHpYuc1EQi1E68AMiL00ZU8oQ3nZpCBBf3MHqAWsfOgH1DtCRuiuVvejdamqOqLbYONp0ZzybA0IFbUY/QGZBkA0EDGMeXHsT+GC9nCfG2YM7DwMGrLFpjsGasPMW47+osDBR46eylKy581N6tYyNdBJ6+Qx3kz970vkr0NxgvV96NQfmR/ocjDNy9aSz+vo3zh9P+FjHrper9YHPBMD3SVI=
services:
- docker
language: go
go:
- 1.13.4
install:
- go get github.com/Masterminds/glide
script:
- make test
- if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} != "true" ]])
  || [[ -n ${TRAVIS_TAG} ]]; then docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD};
  VERSION="latest" make docker-release; fi
before_deploy:
- NAME=GOOS=linux GOARCH=amd64 go build -o bin/vault-lego-linux-amd64
after_deploy:
- docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}
- VERSION=$TRAVIS_TAG make docker-release
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: catac/vault-lego
    tags: true
  api_key:
    secure: "${GITHUB_TOKEN}"
  file: bin/vault-lego-linux-amd64
