env:
  global:
  - REGISTRY_USERNAME=catac
  - secure: BYHR93T+t00xp5aXiKNd6NVReiGbIq01Llwt0Hiu8b0lByVSdvWZLMTZJpypwATHTK8C/Mvvlug9w6EHieopdDnd58d5buEsyuMtv79EgERm8DK2U2+VWceDTrHPnKbV6njTgcHQ18km3AU3EfbotCh7hQftJSCFjxHUtBMF24VymP5EQecJyh42iIwitnZiGp6q7sQUUZz/9lr7SS+WLywtQ4xrG2BkjzJIhJ+KavFtlQW4NhLmyJkfbdPkBagER16+gXD+LaOc3QrrhRkSIGn1ojqVqi+O8NZlGoK2s9AdVK7cXlawQ3in5irug2eHnDN9Yh0xfj+nsSTy3bedPYV6ESjlZTQ2+JCMCbxEIYCfsOonNSkacLW0/Asq8p4048uhVumUpoDcu8DCmvAG4YRn9JS4cwZXmfDCzWPwzRAlAvzVO9s+k5+yuC2vXwjlkoBynW0O0x5TeiuTYIAM4ZgQbh1LtQa/h1FEGm7+yoCNbTqLB8QtuOAecInyFqu2+M2iMsIDvKh8ZIt9bhwt9YEh0Ge8tED0SruNkdsypMz08SoQ/chTTpyeozgIFqA5rH47nMWzak98mmh87AHImGM/WoNiB93jie8OfQy71Y7pE1uvn8gguRxowAAUQ8c9RbWVWigq2i68cbaKaXBinzb5LLTdIB3kOI15OX5t++E=
  - secure: dUTyHTU/ABvs9MigahoU3cjAp3V2mPJQ8tk1kkaW14+NhgjzzNeXktAeeZUMh8bdgcYe3VOfPhH8dD61q96wrU+r76FThBQEGclS21KqjGWUiTBk5jnH3LfAUB7C9qGJo49xCDJXtR54dznZUSGL0HGWe2M6dk2byH4ZcrOuK8b5IjULPiX58J3SJhItA2AEkn6Hf+LVAfagUCd1FOTKunEFLCctWm7c3OhuNdlFwRP3J2CcC/022cEUZuQQccP2IXRjunvnub4keA/QaCjdEOWtRhfnjyjjzbPZq0X+FyL2mqu6Y8Oq3C08s7xDbwLmGKd386N6pOezDY4ql7MridEcF91x9P3RyrB9ihXayCk7YjBSaKIWkEGKdMd1PO5creai/8+TtnlmiG3CqwJ5P55pLv/FIJ9NT4Z4h/lw6WHuOiqKNLAAknENl0zI2TEPnu82CHbqfMezNQrtNYVPM13DirLWIJ7SygzemSnWw0XqJEra8wgLtcwOzaQjzNua7beh5xVC5yRSyIu8RD9g62jivmwxXN7aXHkCTCbacG9jx54m57richBgs3zJtk8g1wQwe+X6fd8VGv4erILFCltTIRcJYTH1/MG1FljSugTn1Du8APZEt0mA5cLm4f9NrpRaPt82JY/zfXx7NcpsSBMgXja3/gNoA1mcKgZTWkY=
services:
- docker
language: go
go:
- 1.9.2
install:
- go get github.com/Masterminds/glide
script:
- make test
- if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} != "true" ]])
  || [[ -n ${TRAVIS_TAG} ]]; then docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD};
  VERSION="latest" make docker-release; fi
before_deploy:
- NAME=GOOS=linux GOARCH=amd64 go build -o bin/vault-lego-linux-amd64
after_deploy:
- docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}
- VERSION=$TRAVIS_TAG make docker-release
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: catac/vault-lego
    tags: true
  api_key:
    secure: "${GITHUB_TOKEN}"
  file: bin/vault-lego-linux-amd64
